import React, { ReactNode } from 'react';
import '@/styles/global.css';
import { Inter } from 'next/font/google';
import GlassPane from '@/components/GlassPane';
import SideBar from '@/components/SideBar';

const inter = Inter({ variable: '--font-inter', subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

function DashboardRootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en" className={inter.variable}>
            <body className="h-screen w-screen candy-mesh p-6">
                <GlassPane className="w-full h-full flex items-center">
                    <SideBar />
                    {children}
                </GlassPane>
                <div id="modal"></div>
            </body>
        </html>
    );
}

export default DashboardRootLayout;
